ALTER USER SALUDMP_HDCWEB DEFAULT ROLE SALUDMP_APLICACION;

-- TABLAS
CREATE PUBLIC SYNONYM VDIR_COLA_SOLICITUD FOR SALUDMP.VDIR_COLA_SOLICITUD;
GRANT SELECT ON  SALUDMP.VDIR_COLA_SOLICITUD TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_COLA_SOLICITUD TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_COLA_SOLICITUD TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_ESTADO FOR SALUDMP.VDIR_ESTADO;
GRANT SELECT ON  SALUDMP.VDIR_ESTADO TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_ESTADO TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_ESTADO TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_BENEFICIARIOS_ASOCIADOS FOR SALUDMP.VDIR_BENEFICIARIOS_ASOCIADOS;
GRANT SELECT ON  SALUDMP.VDIR_BENEFICIARIOS_ASOCIADOS TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_BENEFICIARIOS_ASOCIADOS TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_BENEFICIARIOS_ASOCIADOS TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_CHATBOT FOR SALUDMP.VDIR_CHATBOT;
GRANT SELECT ON  SALUDMP.VDIR_CHATBOT TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_CHATBOT TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_CHATBOT TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_ENCUESTA FOR SALUDMP.VDIR_ENCUESTA;
GRANT SELECT ON  SALUDMP.VDIR_ENCUESTA TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_ENCUESTA TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_ENCUESTA TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_EPS FOR SALUDMP.VDIR_EPS;
GRANT SELECT ON  SALUDMP.VDIR_EPS TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_EPS TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_EPS TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_ESTADO_CIVIL FOR SALUDMP.VDIR_ESTADO_CIVIL;
GRANT SELECT ON  SALUDMP.VDIR_ESTADO_CIVIL TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_ESTADO_CIVIL TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_ESTADO_CIVIL TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_LOG_USUARIOS_SISTEMA FOR SALUDMP.VDIR_LOG_USUARIOS_SISTEMA;
GRANT SELECT ON  SALUDMP.VDIR_LOG_USUARIOS_SISTEMA TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_LOG_USUARIOS_SISTEMA TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_LOG_USUARIOS_SISTEMA TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_LOGOS FOR SALUDMP.VDIR_LOGOS;
GRANT SELECT ON  SALUDMP.VDIR_LOGOS TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_LOGOS TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_LOGOS TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_MENU FOR SALUDMP.VDIR_MENU;
GRANT SELECT ON  SALUDMP.VDIR_MENU TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_MENU TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_MENU TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_LOGOS TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_PAIS FOR SALUDMP.VDIR_PAIS;
GRANT SELECT ON  SALUDMP.VDIR_PAIS TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_PAIS TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_PAIS TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_PARAMETRO FOR SALUDMP.VDIR_PARAMETRO;
GRANT SELECT ON  SALUDMP.VDIR_PARAMETRO TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_PARAMETRO TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_PARAMETRO TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_COMUNA FOR SALUDMP.VDIR_COMUNA;
GRANT SELECT ON  SALUDMP.VDIR_COMUNA TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_COMUNA TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_COMUNA TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_CONDICION_TARIFA FOR SALUDMP.VDIR_CONDICION_TARIFA;
GRANT SELECT ON  SALUDMP.VDIR_CONDICION_TARIFA TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_CONDICION_TARIFA TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_CONDICION_TARIFA TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_DEPARTAMENTO FOR SALUDMP.VDIR_DEPARTAMENTO;
GRANT SELECT ON  SALUDMP.VDIR_DEPARTAMENTO TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_DEPARTAMENTO TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_DEPARTAMENTO TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_FORMA_PAGO FOR SALUDMP.VDIR_FORMA_PAGO;
GRANT SELECT ON  SALUDMP.VDIR_FORMA_PAGO TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_FORMA_PAGO TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_FORMA_PAGO TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_IMPUESTO FOR SALUDMP.VDIR_IMPUESTO;
GRANT SELECT ON  SALUDMP.VDIR_IMPUESTO TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_IMPUESTO TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_IMPUESTO TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_MODULO_ENCUESTA FOR SALUDMP.VDIR_MODULO_ENCUESTA;
GRANT SELECT ON  SALUDMP.VDIR_MODULO_ENCUESTA TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_MODULO_ENCUESTA TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_MODULO_ENCUESTA TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_MONEDA FOR SALUDMP.VDIR_MONEDA;
GRANT SELECT ON  SALUDMP.VDIR_MONEDA TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_MONEDA TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_MONEDA TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_MUNICIPIO FOR SALUDMP.VDIR_MUNICIPIO;
GRANT SELECT ON  SALUDMP.VDIR_MUNICIPIO TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_MUNICIPIO TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_MUNICIPIO TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_NUM_USUARIOS_TARIFA FOR SALUDMP.VDIR_NUM_USUARIOS_TARIFA;
GRANT SELECT ON  SALUDMP.VDIR_NUM_USUARIOS_TARIFA TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_NUM_USUARIOS_TARIFA TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_NUM_USUARIOS_TARIFA TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_PAGINA FOR SALUDMP.VDIR_PAGINA;
GRANT SELECT ON  SALUDMP.VDIR_PAGINA TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_PAGINA TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_PAGINA TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_PAGINA_ROL FOR SALUDMP.VDIR_PAGINA_ROL;
GRANT SELECT ON  SALUDMP.VDIR_PAGINA_ROL TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_PAGINA_ROL TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_PAGINA_ROL TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_PARENTESCO FOR SALUDMP.VDIR_PARENTESCO;
GRANT SELECT ON  SALUDMP.VDIR_PARENTESCO TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_PARENTESCO TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_PARENTESCO TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_PLAN FOR SALUDMP.VDIR_PLAN;
GRANT SELECT ON  SALUDMP.VDIR_PLAN TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_PLAN TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_PLAN TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_PREGUNTA FOR SALUDMP.VDIR_PREGUNTA;
GRANT SELECT ON  SALUDMP.VDIR_PREGUNTA TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_PREGUNTA TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_PREGUNTA TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_PRODUCTO FOR SALUDMP.VDIR_PRODUCTO;
GRANT SELECT ON  SALUDMP.VDIR_PRODUCTO TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_PRODUCTO TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_PRODUCTO TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_PROGRAMA FOR SALUDMP.VDIR_PROGRAMA;
GRANT SELECT ON  SALUDMP.VDIR_PROGRAMA TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_PROGRAMA TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_PROGRAMA TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_PROGRAMA_COTIZADOR FOR SALUDMP.VDIR_PROGRAMA_COTIZADOR;
GRANT SELECT ON  SALUDMP.VDIR_PROGRAMA_COTIZADOR TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_PROGRAMA_COTIZADOR TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_PROGRAMA_COTIZADOR TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_FILE FOR SALUDMP.VDIR_FILE;
GRANT SELECT ON  SALUDMP.VDIR_FILE TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_FILE TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_FILE TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_PROGRAMA_FILE FOR SALUDMP.VDIR_PROGRAMA_FILE;
GRANT SELECT ON  SALUDMP.VDIR_PROGRAMA_FILE TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_PROGRAMA_FILE TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_PROGRAMA_FILE TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_PROMOCIONES FOR SALUDMP.VDIR_PROMOCIONES;
GRANT SELECT ON  SALUDMP.VDIR_PROMOCIONES TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_PROMOCIONES TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_PROMOCIONES TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM PER_REGIONAL FOR SALUDMP.PER_REGIONAL;
GRANT SELECT ON  SALUDMP.PER_REGIONAL TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.PER_REGIONAL TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.PER_REGIONAL TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_REGIONAL FOR SALUDMP.VDIR_REGIONAL;
GRANT SELECT ON  SALUDMP.VDIR_REGIONAL TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_REGIONAL TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_REGIONAL TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM NEXOS_CIUDAD FOR SALUDMP.NEXOS_CIUDAD;
GRANT SELECT ON  SALUDMP.NEXOS_CIUDAD TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.NEXOS_CIUDAD TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.NEXOS_CIUDAD TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_REGIONAL_CIUDAD FOR SALUDMP.VDIR_REGIONAL_CIUDAD;
GRANT SELECT ON  SALUDMP.VDIR_REGIONAL_CIUDAD TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_REGIONAL_CIUDAD TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_REGIONAL_CIUDAD TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_RESPUESTA FOR SALUDMP.VDIR_RESPUESTA;
GRANT SELECT ON  SALUDMP.VDIR_RESPUESTA TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_RESPUESTA TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_RESPUESTA TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_ROL FOR SALUDMP.VDIR_ROL;
GRANT SELECT ON  SALUDMP.VDIR_ROL TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_ROL TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_ROL TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_SEGURO FOR SALUDMP.VDIR_SEGURO;
GRANT SELECT ON  SALUDMP.VDIR_SEGURO TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_SEGURO TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_SEGURO TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_SEXO FOR SALUDMP.VDIR_SEXO;
GRANT SELECT ON  SALUDMP.VDIR_SEXO TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_SEXO TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_SEXO TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_TARIFA_PROGRAMA FOR SALUDMP.VDIR_TARIFA_PROGRAMA;
GRANT SELECT ON  SALUDMP.VDIR_TARIFA_PROGRAMA TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_TARIFA_PROGRAMA TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_TARIFA_PROGRAMA TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_SEXO TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_TARIFAS_ASOCIADAS FOR SALUDMP.VDIR_TARIFAS_ASOCIADAS;
GRANT SELECT ON  SALUDMP.VDIR_TARIFAS_ASOCIADAS TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_TARIFAS_ASOCIADAS TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_TARIFAS_ASOCIADAS TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_TERMINOSCONDICIONES FOR SALUDMP.VDIR_TERMINOSCONDICIONES;
GRANT SELECT ON  SALUDMP.VDIR_TERMINOSCONDICIONES TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_TERMINOSCONDICIONES TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_TERMINOSCONDICIONES TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_TIPO_FILE FOR SALUDMP.VDIR_TIPO_FILE;
GRANT SELECT ON  SALUDMP.VDIR_TIPO_FILE TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_TIPO_FILE TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_TIPO_FILE TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_TIPO_IDENTIFICACION FOR SALUDMP.VDIR_TIPO_IDENTIFICACION;
GRANT SELECT ON  SALUDMP.VDIR_TIPO_IDENTIFICACION TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_TIPO_IDENTIFICACION TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_TIPO_IDENTIFICACION TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_TIPO_PAGO FOR SALUDMP.VDIR_TIPO_PAGO;
GRANT SELECT ON  SALUDMP.VDIR_TIPO_PAGO TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_TIPO_PAGO TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_TIPO_PAGO TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_TIPO_PERSONA FOR SALUDMP.VDIR_TIPO_PERSONA;
GRANT SELECT ON  SALUDMP.VDIR_TIPO_PERSONA TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_TIPO_PERSONA TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_TIPO_PERSONA TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_TIPO_SOLICITUD FOR SALUDMP.VDIR_TIPO_SOLICITUD;
GRANT SELECT ON  SALUDMP.VDIR_TIPO_SOLICITUD TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_TIPO_SOLICITUD TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_TIPO_SOLICITUD TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_TIPO_TARIFA FOR SALUDMP.VDIR_TIPO_TARIFA;
GRANT SELECT ON  SALUDMP.VDIR_TIPO_TARIFA TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_TIPO_TARIFA TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_TIPO_TARIFA TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_TIPO_VIA FOR SALUDMP.VDIR_TIPO_VIA;
GRANT SELECT ON  SALUDMP.VDIR_TIPO_VIA TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_TIPO_VIA TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_TIPO_VIA TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_BARRIO FOR SALUDMP.VDIR_BARRIO;
GRANT SELECT ON  SALUDMP.VDIR_BARRIO TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_BARRIO TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_BARRIO TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_COBERTURA FOR SALUDMP.VDIR_COBERTURA;
GRANT SELECT ON  SALUDMP.VDIR_COBERTURA TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_COBERTURA TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_COBERTURA TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_PARAMETROS_PROGRAMA FOR SALUDMP.VDIR_PARAMETROS_PROGRAMA;
GRANT SELECT ON  SALUDMP.VDIR_PARAMETROS_PROGRAMA TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_PARAMETROS_PROGRAMA TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_PARAMETROS_PROGRAMA TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_PERSONA FOR SALUDMP.VDIR_PERSONA;
GRANT SELECT ON  SALUDMP.VDIR_PERSONA TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_PERSONA TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_PERSONA TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_PARAMETROS_PROGRAMA TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_PERSONA_TIPOPER FOR SALUDMP.VDIR_PERSONA_TIPOPER;
GRANT SELECT ON  SALUDMP.VDIR_PERSONA_TIPOPER TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_PERSONA_TIPOPER TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_PERSONA_TIPOPER TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_PLAN_PROGRAMA FOR SALUDMP.VDIR_PLAN_PROGRAMA;
GRANT SELECT ON  SALUDMP.VDIR_PLAN_PROGRAMA TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_PLAN_PROGRAMA TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_PLAN_PROGRAMA TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_RESPUESTAS_MARCADAS FOR SALUDMP.VDIR_RESPUESTAS_MARCADAS;
GRANT SELECT ON  SALUDMP.VDIR_RESPUESTAS_MARCADAS TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_RESPUESTAS_MARCADAS TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_RESPUESTAS_MARCADAS TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_TARIFA FOR SALUDMP.VDIR_TARIFA;
GRANT SELECT ON  SALUDMP.VDIR_TARIFA TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_TARIFA TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_TARIFA TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_TARIFA_FILE FOR SALUDMP.VDIR_TARIFA_FILE;
GRANT SELECT ON  SALUDMP.VDIR_TARIFA_FILE TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_TARIFA_FILE TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_TARIFA_FILE TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_COBERTURAPROGRAMA FOR SALUDMP.VDIR_COBERTURAPROGRAMA;
GRANT SELECT ON  SALUDMP.VDIR_COBERTURAPROGRAMA TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_COBERTURAPROGRAMA TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_COBERTURAPROGRAMA TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_ENCUESTA_PERSONA FOR SALUDMP.VDIR_ENCUESTA_PERSONA;
GRANT SELECT ON  SALUDMP.VDIR_ENCUESTA_PERSONA TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_ENCUESTA_PERSONA TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_ENCUESTA_PERSONA TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_USUARIO FOR SALUDMP.VDIR_USUARIO;
GRANT SELECT ON  SALUDMP.VDIR_USUARIO TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_USUARIO TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_USUARIO TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_ROL_USUARIO FOR SALUDMP.VDIR_ROL_USUARIO;
GRANT SELECT ON  SALUDMP.VDIR_ROL_USUARIO TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_ROL_USUARIO TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_ROL_USUARIO TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_AFILIACION FOR SALUDMP.VDIR_AFILIACION;
GRANT SELECT ON  SALUDMP.VDIR_AFILIACION TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_AFILIACION TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_AFILIACION TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_ROL_USUARIO TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_AFILIACION_AUDITORIA FOR SALUDMP.VDIR_AFILIACION_AUDITORIA;
GRANT SELECT ON  SALUDMP.VDIR_AFILIACION_AUDITORIA TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_AFILIACION_AUDITORIA TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_AFILIACION_AUDITORIA TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_BENEFICIARIO_PROGRAMA FOR SALUDMP.VDIR_BENEFICIARIO_PROGRAMA;
GRANT SELECT ON  SALUDMP.VDIR_BENEFICIARIO_PROGRAMA TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_BENEFICIARIO_PROGRAMA TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_BENEFICIARIO_PROGRAMA TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_BITACORA_SOLICITUD FOR SALUDMP.VDIR_BITACORA_SOLICITUD;
GRANT SELECT ON  SALUDMP.VDIR_BITACORA_SOLICITUD TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_BITACORA_SOLICITUD TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_BITACORA_SOLICITUD TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_COLA_SOLICITUD FOR SALUDMP.VDIR_COLA_SOLICITUD;
GRANT SELECT ON  SALUDMP.VDIR_COLA_SOLICITUD TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_COLA_SOLICITUD TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_COLA_SOLICITUD TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_CONTRATANTE_BENEFICIARIO FOR SALUDMP.VDIR_CONTRATANTE_BENEFICIARIO;
GRANT SELECT ON  SALUDMP.VDIR_CONTRATANTE_BENEFICIARIO TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_CONTRATANTE_BENEFICIARIO TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_CONTRATANTE_BENEFICIARIO TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_FACTURA FOR SALUDMP.VDIR_FACTURA;
GRANT SELECT ON  SALUDMP.VDIR_FACTURA TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_FACTURA TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_FACTURA TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_FACTURA_DETALLE FOR SALUDMP.VDIR_FACTURA_DETALLE;
GRANT SELECT ON  SALUDMP.VDIR_FACTURA_DETALLE TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_FACTURA_DETALLE TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_FACTURA_DETALLE TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_FILE_AUDITORIA FOR SALUDMP.VDIR_FILE_AUDITORIA;
GRANT SELECT ON  SALUDMP.VDIR_FILE_AUDITORIA TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_FILE_AUDITORIA TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_FILE_AUDITORIA TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_FILE_BENEFICIARIO FOR SALUDMP.VDIR_FILE_BENEFICIARIO;
GRANT SELECT ON  SALUDMP.VDIR_FILE_BENEFICIARIO TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_FILE_BENEFICIARIO TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_FILE_BENEFICIARIO TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_PERSONA_CONTRATO FOR SALUDMP.VDIR_PERSONA_CONTRATO;
GRANT SELECT ON  SALUDMP.VDIR_PERSONA_CONTRATO TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_PERSONA_CONTRATO TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_PERSONA_CONTRATO TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_PERSONA_CONTRATO FOR SALUDMP.VDIR_PERSONA_CONTRATO;
GRANT SELECT ON  SALUDMP.VDIR_PERSONA_CONTRATO TO SALUDMP_APLICACION;
GRANT INSERT ON  SALUDMP.VDIR_PERSONA_CONTRATO TO SALUDMP_APLICACION;
GRANT UPDATE ON  SALUDMP.VDIR_PERSONA_CONTRATO TO SALUDMP_APLICACION;