ALTER USER SALUDMP_HDCWEB DEFAULT ROLE SALUDMP_APLICACION;

-- PAQUETES
CREATE PUBLIC SYNONYM VDIR_PACK_BANDEJA_OPERACIONES FOR SALUDMP.VDIR_PACK_BANDEJA_OPERACIONES;
GRANT EXECUTE ON  SALUDMP.VDIR_PACK_BANDEJA_OPERACIONES TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_PACK_CONSULTA_CONTRATO FOR SALUDMP.VDIR_PACK_CONSULTA_CONTRATO;
GRANT EXECUTE ON  SALUDMP.VDIR_PACK_CONSULTA_CONTRATO TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_PACK_CONSULTA_USUARIOS FOR SALUDMP.VDIR_PACK_CONSULTA_USUARIOS;
GRANT EXECUTE ON  SALUDMP.VDIR_PACK_CONSULTA_USUARIOS TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_PACK_CONSULTA_FILE FOR SALUDMP.VDIR_PACK_CONSULTA_FILE;
GRANT EXECUTE ON  SALUDMP.VDIR_PACK_CONSULTA_FILE TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_PACK_CONSULTA_LINEAS FOR SALUDMP.VDIR_PACK_CONSULTA_LINEAS;
GRANT EXECUTE ON  SALUDMP.VDIR_PACK_CONSULTA_LINEAS TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_PACK_CONSULTA_SOLICITUD FOR SALUDMP.VDIR_PACK_CONSULTA_SOLICITUD;
GRANT EXECUTE ON  SALUDMP.VDIR_PACK_CONSULTA_SOLICITUD TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_PACK_CONSULTA_TARIFAS FOR SALUDMP.VDIR_PACK_CONSULTA_TARIFAS;
GRANT EXECUTE ON  SALUDMP.VDIR_PACK_CONSULTA_TARIFAS TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_PACK_ENVIAR_EMAIL FOR SALUDMP.VDIR_PACK_ENVIAR_EMAIL;
GRANT EXECUTE ON  SALUDMP.VDIR_PACK_ENVIAR_EMAIL TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_PACK_ENCUESTAS FOR SALUDMP.VDIR_PACK_ENCUESTAS;
GRANT EXECUTE ON  SALUDMP.VDIR_PACK_ENCUESTAS TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_PACK_INICIO_SESSION FOR SALUDMP.VDIR_PACK_INICIO_SESSION;
GRANT EXECUTE ON  SALUDMP.VDIR_PACK_INICIO_SESSION TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_PACK_REGISTRO_CONTRATO FOR SALUDMP.VDIR_PACK_REGISTRO_CONTRATO;
GRANT EXECUTE ON  SALUDMP.VDIR_PACK_REGISTRO_CONTRATO TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_PACK_REGISTRO_DATOS FOR SALUDMP.VDIR_PACK_REGISTRO_DATOS;
GRANT EXECUTE ON  SALUDMP.VDIR_PACK_REGISTRO_DATOS TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_PACK_REGISTRO_FILE FOR SALUDMP.VDIR_PACK_REGISTRO_FILE;
GRANT EXECUTE ON  SALUDMP.VDIR_PACK_REGISTRO_FILE TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_PACK_REGISTRO_LINEAS FOR SALUDMP.VDIR_PACK_REGISTRO_LINEAS;
GRANT EXECUTE ON  SALUDMP.VDIR_PACK_REGISTRO_LINEAS TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_PACK_REGISTRO_PRODUCTOS FOR SALUDMP.VDIR_PACK_REGISTRO_PRODUCTOS;
GRANT EXECUTE ON  SALUDMP.VDIR_PACK_REGISTRO_PRODUCTOS TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_PACK_REGISTRO_TARIFAS FOR SALUDMP.VDIR_PACK_REGISTRO_TARIFAS;
GRANT EXECUTE ON  SALUDMP.VDIR_PACK_REGISTRO_TARIFAS TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_PACK_REGISTRO_USUARIOS FOR SALUDMP.VDIR_PACK_REGISTRO_USUARIOS;
GRANT EXECUTE ON  SALUDMP.VDIR_PACK_REGISTRO_USUARIOS TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_PACK_TARIFAS FOR SALUDMP.VDIR_PACK_TARIFAS;
GRANT EXECUTE ON  SALUDMP.VDIR_PACK_TARIFAS TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM VDIR_PACK_UTILIDADES FOR SALUDMP.VDIR_PACK_UTILIDADES;
GRANT EXECUTE ON  SALUDMP.VDIR_PACK_UTILIDADES TO SALUDMP_APLICACION;
