create
or replace PACKAGE VDIR_PACK_ENVIAR_EMAIL AS FUNCTION send_email (
    REMITE IN VARCHAR2,
    DESTINO IN VARCHAR2,
    ASUNTO IN VARCHAR2,
    MENSAJE IN VARCHAR2,
    PUERTO IN NUMBER,
    SERVIDOR IN VARCHAR2,
    USUARIO IN VARCHAR2,
    CLAVE IN VARCHAR2
) RETURN VARCHAR2;

FUNCTION send_email2 (
    REMITE IN VARCHAR2,
    DESTINO IN VARCHAR2,
    ASUNTO IN VARCHAR2,
    MENSAJE IN CLOB,
    PUERTO IN NUMBER,
    SERVIDOR IN VARCHAR2,
    USUARIO IN VARCHAR2,
    CLAVE IN VARCHAR2,
    MENSAJE2 IN CLOB
) RETURN VARCHAR2;

PROCEDURE add_destinatatios (
    P_MAIL_CONN IN OUT UTL_SMTP.CONNECTION,
    P_LIST IN VARCHAR2
);

END VDIR_PACK_ENVIAR_EMAIL;