create
or replace PACKAGE VDIR_PACK_TARIFAS AS
-------------------FUNCION PARA TRAER LAS IMAGENES DE LAS PROMOCIONES
FUNCTION VDIR_FN_GET_DATOS_PROMO_IMG RETURN sys_refcursor;

-------------------- PROCEDIMIENTO PARA GUARDAR LAS IMAGNES DE LAS PROMOCIONES
PROCEDURE VDIR_SP_SAVE_PROMO_IMG (
    p_name IN VARCHAR2,
    p_name_encript IN VARCHAR2,
    p_ruta IN VARCHAR2,
    p_respuesta OUT VARCHAR2
);

-------------------- PROCEDIMIENTO PARA ELIMINAR UNA IMAGEN
PROCEDURE VDIR_SP_DELETE_PROMO_IMG (
    p_codigo_imagen IN NUMBER,
    p_respuesta OUT VARCHAR2
);

END VDIR_PACK_TARIFAS;