CREATE or REPLACE TRIGGER TRIG_SEQ_POR_ESP_X_CIU BEFORE
INSERT ON POR_ESPECIALIDAD_X_CIUDAD FOR EACH ROW BEGIN
SELECT SEQ_POR_ESPECIALIDAD_X_CIUDAD.nextval INTO :new.ID
FROM dual;
END;
/

ALTER TABLE POR_CIUDAD
MODIFY ID NUMBER(10) DEFAULT SEQ_POR_CIUDAD.NEXTVAL;

ALTER TABLE POR_ESPECIALIDAD
MODIFY ID NUMBER(10) DEFAULT SEQ_POR_ESPECIALIDAD.NEXTVAL;

ALTER TABLE POR_ESPECIALIDAD_X_CIUDAD
MODIFY ID NUMBER(10) DEFAULT SEQ_POR_ESPECIALIDAD_X_CIUDAD.NEXTVAL;