ALTER TABLE POR_CENTROS_MEDICOS DROP COLUMN ID_MEDICAL_CENTER;

ALTER TABLE POR_CENTROS_MEDICOS DROP COLUMN SPECIALITY;

ALTER TABLE POR_CENTROS_MEDICOS ADD STATUS NUMBER(38,0);

ALTER TABLE POR_CENTROS_MEDICOS ADD ADDRESS_2 VARCHAR(255 BYTE);


