

CREATE SEQUENCE  SEQ_POR_CIUDAD
MINVALUE 1 
MAXVALUE 999999999999999999999999999 
INCREMENT BY 1 
START WITH 1 
CACHE 20 
NOORDER  
NOCYCLE ;

CREATE SEQUENCE  SEQ_POR_ESPECIALIDAD
MINVALUE 1 
MAXVALUE 999999999999999999999999999 
INCREMENT BY 1 
START WITH 1 
CACHE 20 
NOORDER  
NOCYCLE ;

CREATE SEQUENCE  SEQ_POR_ESPECIALIDAD_X_CIUDAD
MINVALUE 1 
MAXVALUE 999999999999999999999999999 
INCREMENT BY 1 
START WITH 1 
CACHE 20 
NOORDER  
NOCYCLE ;


CREATE or REPLACE TRIGGER TRIG_SEQ_POR_CIUDAD
BEFORE INSERT ON POR_CIUDAD
FOR EACH ROW
BEGIN
SELECT SEQ_POR_CIUDAD.nextval INTO :new.ID FROM dual;
END;
/

CREATE or REPLACE TRIGGER TRIG_SEQ_POR_ESPECIALIDAD
BEFORE INSERT ON POR_ESPECIALIDAD
FOR EACH ROW
BEGIN
SELECT SEQ_POR_ESPECIALIDAD.nextval INTO :new.ID FROM dual;
END;
/

CREATE or REPLACE TRIGGER TRIG_SEQ_POR_ESPECIALIDAD_X_CIUDAD
BEFORE INSERT ON POR_ESPECIALIDAD_X_CIUDAD
FOR EACH ROW
BEGIN
SELECT SEQ_POR_ESPECIALIDAD_X_CIUDAD.nextval INTO :new.ID FROM dual;
END;
/


ALTER TABLE POR_CIUDAD MODIFY ID NUMBER DEFAULT  SEQ_POR_CIUDAD.NEXTVAL;
ALTER TABLE POR_ESPECIALIDAD MODIFY ID NUMBER DEFAULT  SEQ_POR_ESPECIALIDAD.NEXTVAL;
ALTER TABLE POR_ESPECIALIDAD_X_CIUDAD MODIFY ID NUMBER DEFAULT  SEQ_POR_ESPECIALIDAD_X_CIUDAD.NEXTVAL;


