CREATE TABLE POR_CENTROS_MEDICOS(
  ID number NOT NULL PRIMARY KEY,
  NAME VARCHAR2(255 CHAR) NOT NULL,
  CITY VARCHAR2(255 CHAR) NOT NULL,
  ADDRESS VARCHAR2(255 CHAR) NOT NULL,
  LAT VARCHAR2(255 CHAR) NOT NULL,
  LON VARCHAR2(255 CHAR) NOT NULL,
  PHONE VARCHAR2(255 CHAR) NOT NULL,
  HOUR_INI VARCHAR2(255 CHAR) NOT NULL,
  HOUR_FIN VARCHAR2(255 CHAR),
  IMAGE VARCHAR2(255 CHAR) NOT NULL,
  STATUS NUMBER(38,0),
  ADDRESS_2 VARCHAR2(255 CHAR) NOT NULL
);
