/* -----------------------------------------------------------------------------
	 Copyright Coomeva S.A. - Colombia
	 Package : PCMED_SNPCentrosMedicos
	 Caso de Uso :
	 Descripción :  Gestiona el modulo de Centros Medicos del App Ayudaventas
	 -------------------------------------------------------------------------------
	 Autor : Jhon Medina
	 Fecha : 22-11-2022
	 -------------------------------------------------------------------------------
	 Historia de Modificaciones:
	 -------------------------------------------------------------------------------
	 Fecha Autor Modificación: 
	 ------------------------------------------------------------------------------*/

create or replace PACKAGE PCMED_SNPCENTROSMEDICOS AS
-- PROCEDIMIENTOS DE TABLA POR_CIUDAD
    PROCEDURE INSERT_POR_CIUDAD(V_CODE IN VARCHAR2,V_NAME IN VARCHAR2, V_STATUS IN VARCHAR2, V_ID OUT NUMBER);
    PROCEDURE UPDATE_POR_CIUDAD(V_ID IN INTEGER, V_CODE IN VARCHAR2,V_NAME IN VARCHAR2, V_STATUS IN VARCHAR2);
    PROCEDURE DELETE_POR_CIUDAD(V_ID IN INTEGER);
-- PROCEDIMIENTOS DE TABLA POR_ESPECIALIDAD    
    PROCEDURE INSERT_POR_ESPECIALIDAD(V_CODE IN VARCHAR2,V_NAME IN VARCHAR2,V_SUBSPECIALTY IN VARCHAR2 DEFAULT 'NULL', V_STATUS IN VARCHAR2, V_ID OUT NUMBER);
    PROCEDURE UPDATE_POR_ESPECIALIDAD(V_ID IN INTEGER, V_CODE IN VARCHAR2,V_NAME IN VARCHAR2,V_SUBSPECIALTY IN VARCHAR2 DEFAULT 'NULL', V_STATUS IN VARCHAR2);
    PROCEDURE DELETE_POR_ESPECIALIDAD(V_ID IN INTEGER);
-- PROCEDIMIENTOS DE TABLA POR_CENTROS_MEDICOS    
    PROCEDURE INSERT_POR_CMEDICOS(V_NAME IN VARCHAR2,V_CITY IN VARCHAR2,V_ADDRESS IN VARCHAR2,V_LAT IN VARCHAR2,V_LON IN VARCHAR2,V_HOUR_INI IN VARCHAR2,V_HOUR_FIN IN VARCHAR2 DEFAULT 'NULL',V_PHONE IN VARCHAR2,V_IMAGE IN VARCHAR2,V_STATUS IN VARCHAR2,V_ADDRESS_2 IN VARCHAR2,V_ID OUT NUMBER);
    PROCEDURE UPDATE_POR_CMEDICOS(V_ID IN INTEGER,V_NAME IN VARCHAR2,V_CITY IN VARCHAR2,V_ADDRESS IN VARCHAR2,V_LAT IN VARCHAR2,V_LON IN VARCHAR2,V_HOUR_INI IN VARCHAR2,V_HOUR_FIN IN VARCHAR2 DEFAULT 'NULL',V_PHONE IN VARCHAR2,V_IMAGE IN VARCHAR2,V_STATUS IN VARCHAR2,V_ADDRESS_2 IN VARCHAR2);
    PROCEDURE DELETE_POR_CMEDICOS(V_ID IN INTEGER);
-- PROCEDIMIENTOS DE TABLA POR_ESP_X_CIUDAD    
    PROCEDURE INSERT_POR_ESP_X_CIUDAD(V_ID_CIU IN INTEGER, V_ID_ESP IN INTEGER);
    PROCEDURE UPDATE_POR_ESP_X_CIUDAD(V_ID IN INTEGER,V_ID_CIU IN INTEGER, V_ID_ESP IN INTEGER);
    PROCEDURE DELETE_POR_ESP_X_CIUDAD(V_IDCIUDAD IN INTEGER);
-- PROCEDIMIENTOS DE TABLA POR_SPECIALTIES
    PROCEDURE INSERT_POR_SPECIALTIES(V_SPECIALTY IN VARCHAR2,V_SUBSPECIALTY IN VARCHAR2 DEFAULT 'NULL',V_MEDICAL_C_ID IN INTEGER, V_STATUS IN VARCHAR2 DEFAULT '1');
    PROCEDURE UPDATE_POR_SPECIALTIES(V_ID IN INTEGER,V_SPECIALTY IN VARCHAR2,V_SUBSPECIALTY IN VARCHAR2 DEFAULT 'NULL',V_MEDICAL_C_ID IN INTEGER, V_STATUS IN VARCHAR2 DEFAULT '1');
    PROCEDURE DELETE_POR_SPECIALTIES(ID_CENTRO_M IN INTEGER);
    END PCMED_SNPCENTROSMEDICOS;


