CREATE OR REPLACE PROCEDURE POR_CENTROS_MEDICOS_INSERT(
    NAME IN VARCHAR2,
    CITY IN VARCHAR2,
    ADDRESS IN VARCHAR2,
    LAT IN VARCHAR2,
    LON IN VARCHAR2,
    HOUR_INI IN VARCHAR2,
    HOUR_FIN IN VARCHAR2,
    PHONE IN VARCHAR2,
    IMAGE IN VARCHAR2,
    STATUS IN INTEGER,
    ADDRESS_2 IN VARCHAR2
  ) 
  AS 
  
  ID NUMBER;
  HOUR_FIN2 VARCHAR2(255);
  
BEGIN 

  IF HOUR_FIN IS NULL THEN
    HOUR_FIN2:=NULL;
  ELSE
    HOUR_FIN2:=HOUR_FIN;
  END IF;
  
  SELECT SEQ_POR_CENTROS_MEDICOS.NEXTVAL INTO ID FROM DUAL;

    INSERT INTO POR_CENTROS_MEDICOS
    VALUES (
        ID,
        NAME,
        CITY,
        ADDRESS,
        LAT,
        LON,
        HOUR_INI,
        HOUR_FIN2,
        PHONE,
        IMAGE,
        STATUS,
        ADDRESS_2
      );
    COMMIT;
END POR_CENTROS_MEDICOS_INSERT;
  
