CREATE OR REPLACE PROCEDURE POR_ESPECIALIDAD_INSERT(CODE in VARCHAR2, NAME in VARCHAR2,SUBSPECIALTY2 VARCHAR, STATUS CHAR )
      AS
          ID INTEGER;
          SUBSPECIALTY VARCHAR2(255);
      BEGIN
      
          SELECT SEQ_POR_ESPECIALIDAD.NEXTVAL INTO ID FROM DUAL;
          
          IF SUBSPECIALTY2 IS NULL THEN
            SUBSPECIALTY:=NULL;
          ELSE
            SUBSPECIALTY:=SUBSPECIALTY2;
          END IF;  
          
          INSERT INTO POR_ESPECIALIDAD VALUES (ID,CODE,NAME,SUBSPECIALTY,STATUS);

          COMMIT;
      END POR_ESPECIALIDAD_INSERT;