CREATE OR REPLACE PROCEDURE POR_CIUDAD_INSERT(CODE2 in VARCHAR2, NAME in VARCHAR2, STATUS CHAR )
      AS
          ID INTEGER;
          CODE VARCHAR2(20);
      BEGIN
      
          SELECT SEQ_POR_CIUDAD.NEXTVAL INTO ID FROM DUAL;
          
          IF CODE2 IS NULL THEN
            CODE:=NULL;
          ELSE
            CODE:=CODE2;
          END IF;  
          
          INSERT INTO POR_CIUDAD VALUES (ID,CODE,NAME,STATUS);
      END POR_CIUDAD_INSERT;