CREATE OR REPLACE PROCEDURE POR_ESP_X_CIUDAD_INSERT (ID_CIUDAD in INTEGER, ID_ESPECIALIDAD in INTEGER) 

AS ID INTEGER;

BEGIN
SELECT
    SEQ_POR_ESPECIALIDAD_X_CIUDAD.NEXTVAL INTO ID
FROM
    DUAL;

INSERT INTO
    POR_ESPECIALIDAD_X_CIUDAD
VALUES
    (ID, ID_CIUDAD, ID_ESPECIALIDAD);

COMMIT;

END POR_ESP_X_CIUDAD_INSERT;