CREATE TABLE SMP_MSC_PRU.MSC_P_CORREO (
    id_correo INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_correo VARCHAR(255),
    nombre_correo VARCHAR(255) NOT NULL,
    cod_aplicacion VARCHAR(50) NOT NULL,
    html CLOB NOT NULL,
    asunto VARCHAR(255) NOT NULL,
    dominio VARCHAR(255) NOT NULL,
    api_user VARCHAR(100) NOT NULL,
    api_key VARCHAR(100) NOT NULL
);

COMMENT ON COLUMN SMP_MSC_PRU.MSC_P_CORREO.cod_correo IS 'Código de correo';
COMMENT ON COLUMN SMP_MSC_PRU.MSC_P_CORREO.nombre_correo IS 'Nombre descriptivo del correo';
COMMENT ON COLUMN SMP_MSC_PRU.MSC_P_CORREO.cod_aplicacion IS 'Código de la aplicación';
COMMENT ON COLUMN SMP_MSC_PRU.MSC_P_CORREO.html IS 'Cuerpo del mensaje en HTML, admite plantillas';
COMMENT ON COLUMN SMP_MSC_PRU.MSC_P_CORREO.asunto IS 'Asunto del correo, admite variables';
COMMENT ON COLUMN SMP_MSC_PRU.MSC_P_CORREO.dominio IS 'Dominio para el envío de correo';
COMMENT ON COLUMN SMP_MSC_PRU.MSC_P_CORREO.api_user IS 'Usuario de API para el envío de correos';
COMMENT ON COLUMN SMP_MSC_PRU.MSC_P_CORREO.api_key IS 'Clave de API para el envío de correos';


INSERT INTO SMP_MSC_DESA.MSC_PRODUCTO
(PROD_ID, NOMBRE, FECHA_CREACION, USUARIO_CREADOR, FECHA_MODIFICACION, USUARIO_MODIFICADOR, ESTADO)
VALUES(10, 'Mail Service', TO_TIMESTAMP(TO_CHAR(SYSTIMESTAMP, 'DD/MM/YY HH12:MI:SS,FF9 AM')), 'dsimbaqueva', NULL, NULL, 'A');





