CREATE TABLE AUT_AUTENTICACION_TICKET (
  CODIGO                   NUMBER(20) NOT NULL   , 
    FECHA_REGISTRO           TIMESTAMP(6)  NOT NULL ,
    IN_TIPO_CREDENCIAL       VARCHAR2(2)  NOT NULL  ,
    IN_DOCUMENTO             VARCHAR2(20)  NOT NULL ,
    IN_CLAVE                VARCHAR2(40)  NOT NULL ,
    IN_REFERENCIA_ORIGEN              VARCHAR2(50)  ,
    OUT_ESTADO_AUTENTICACION          VARCHAR2(5)   ,
    OUT_TIECKET_REFERENCIA            NUMBER(10)    ,
    OUT_URL                           VARCHAR2(200) ,
    OUT_COD_ERROR                     VARCHAR2(3)   ,
    OUT_ERROR                         VARCHAR2(100) ,
    FECHA_EXPIRA                      TIMESTAMP(6) 
)


CREATE SEQUENCE AUT_AUTENTICACION_TICKET_SEQ
  MINVALUE 1
  MAXVALUE 999999999999999999999999999
  INCREMENT BY 1
  START WITH 1
  CACHE 20
  NOORDER
  NOCYCLE;
  