
INSERT INTO GEN_MODULO VALUES (2,'PROFILE');

INSERT INTO GEN_TIPO_CAMBIO VALUES (13,'AUT_USUARIO_ESTADO, cambia el estado del usuario','AUT_USUARIO.ESTADO',1) ;
INSERT INTO GEN_TIPO_CAMBIO VALUES (14,'AUT_APLICACIONES_USUARIO_ESTADO, cambia el estado de las aplicaciones asociadas a un usuario','AUT_APLICACIONES_USUARIO.ESTADO',1) ;
INSERT INTO GEN_TIPO_CAMBIO VALUES (15,'AUT_ROLES_USUARIO_APLICACION_ESTADO, cambia el estado de los roles asociadas a un usuario','AUT_ROLES_USUARIO_APLICACION.ESTADO',1) ;

INSERT INTO GEN_PERMISO_USUARIO VALUES (131,13, 'jimb8316') ;
INSERT INTO GEN_PERMISO_USUARIO VALUES (132,14,'jimb8316') ;
INSERT INTO GEN_PERMISO_USUARIO VALUES (133,15,'jimb8316') ;

INSERT INTO GEN_PERMISO_USUARIO VALUES (134,13,'mamb8250');
INSERT INTO GEN_PERMISO_USUARIO VALUES (135,14,'mamb8250');
INSERT INTO GEN_PERMISO_USUARIO VALUES (136,15,'mamb8250');

INSERT INTO GEN_PERMISO_USUARIO VALUES (137,13,'jjic4960');
INSERT INTO GEN_PERMISO_USUARIO VALUES (138,14,'jjic4960');
INSERT INTO GEN_PERMISO_USUARIO VALUES (139,15,'jjic4960');

INSERT INTO GEN_PERMISO_USUARIO VALUES (140,13,'cacg9802');
INSERT INTO GEN_PERMISO_USUARIO VALUES (141,14,'cacg9802');
INSERT INTO GEN_PERMISO_USUARIO VALUES (142,15,'cacg9802');

INSERT INTO GEN_PERMISO_USUARIO VALUES (143,13,'gfbp2913');
INSERT INTO GEN_PERMISO_USUARIO VALUES (144,14,'gfbp2913');
INSERT INTO GEN_PERMISO_USUARIO VALUES (145,15,'gfbp2913');

COMMIT;


SELECT * FROM GEN_MODULO;
SELECT * FROM GEN_TIPO_CAMBIO WHERE COD_TIPO_CAMBIO in (13,14,15);
SELECT * FROM GEN_PERMISO_USUARIO WHERE COD_TIPO_CAMBIO in (13,14,15);
SELECT * FROM GEN_BITACORA_CAMBIO;