INSERT INTO aut_aplicaciones VALUES (109,'Hora de Cuidarme Operativo',SYSDATE,'A','NO','NO',NULL,NULL);
INSERT INTO aut_aplicaciones VALUES (110,'Hora de Cuidarme Admon',SYSDATE,'A','NO','NO',NULL,NULL);
COMMIT;



SELECT * FROM GEN_TIPO_CAMBIO WHERE COD_TIPO_CAMBIO in (13,14,15);
-- INSERT INTO GEN_TIPO_CAMBIO VALUES (13,'AUT_USUARIO_ESTADO, cambia el estado del usuario','AUT_USUARIO.ESTADO',1) ;
-- INSERT INTO GEN_TIPO_CAMBIO VALUES (14,'AUT_APLICACIONES_USUARIO_ESTADO, cambia el estado de las aplicaciones asociadas a un usuario','AUT_APLICACIONES_USUARIO.ESTADO',1) ;
-- INSERT INTO GEN_TIPO_CAMBIO VALUES (15,'AUT_ROLES_USUARIO_APLICACION_ESTADO, cambia el estado de los roles asociadas a un usuario','AUT_ROLES_USUARIO_APLICACION.ESTADO',1) ;

SELECT * FROM GEN_PERMISO_USUARIO WHERE COD_TIPO_CAMBIO in (13,14,15);

-- Pruebas
INSERT INTO GEN_PERMISO_USUARIO VALUES (14,13, 'jimb8316') ;
INSERT INTO GEN_PERMISO_USUARIO VALUES (15,14,'jimb8316') ;
INSERT INTO GEN_PERMISO_USUARIO VALUES (16,15,'jimb8316') ;

INSERT INTO GEN_PERMISO_USUARIO VALUES (17,13,'mamb8250');
INSERT INTO GEN_PERMISO_USUARIO VALUES (18,14,'mamb8250');
INSERT INTO GEN_PERMISO_USUARIO VALUES (19,15,'mamb8250');

INSERT INTO GEN_PERMISO_USUARIO VALUES (20,13,'jjic4960');
INSERT INTO GEN_PERMISO_USUARIO VALUES (21,14,'jjic4960');
INSERT INTO GEN_PERMISO_USUARIO VALUES (22,15,'jjic4960');

INSERT INTO GEN_PERMISO_USUARIO VALUES (23,13,'cacg9802');
INSERT INTO GEN_PERMISO_USUARIO VALUES (24,14,'cacg9802');
INSERT INTO GEN_PERMISO_USUARIO VALUES (25,15,'cacg9802');

INSERT INTO GEN_PERMISO_USUARIO VALUES (26,13,'gfbp2913');
INSERT INTO GEN_PERMISO_USUARIO VALUES (27,14,'gfbp2913');
INSERT INTO GEN_PERMISO_USUARIO VALUES (28,15,'gfbp2913');

COMMIT;
