CREATE SEQUENCE VDIR_GUARDAR_RECIBO_SEQ
  START WITH 1       
  INCREMENT BY 1    
  MINVALUE 1        
  MAXVALUE 999999999999999999999999999 
  CYCLE           
  CACHE 20;


CREATE PUBLIC SYNONYM VDIR_GUARDAR_RECIBO_SEQ FOR SALUDMP.VDIR_GUARDAR_RECIBO_SEQ;
GRANT SELECT ON  SALUDMP.VDIR_GUARDAR_RECIBO_SEQ TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM AUTO_INCREMENT_TARASOC FOR SALUDMP.AUTO_INCREMENT_TARASOC;
GRANT SELECT ON  SALUDMP.AUTO_INCREMENT_TARASOC TO SALUDMP_APLICACION;


CREATE OR REPLACE TRIGGER AUTO_INCREMENT_TARASOC 
   BEFORE INSERT ON VDIR_TARIFAS_ASOCIADAS
   FOR EACH ROW
BEGIN
   SELECT AUTO_INCREMENT_TARASOC.nextval
   INTO :new.COD_BENEFICIARIO
   FROM dual;
END;

CREATE PUBLIC SYNONYM AUTO_INCREMENT_TARASOC FOR SALUDMP.AUTO_INCREMENT_TARASOC;
GRANT EXECUTE ON  SALUDMP.AUTO_INCREMENT_TARASOC TO SALUDMP_APLICACION;