CREATE SEQUENCE SEQ_AUTO_INCREMENT_PROMOCIONES
  START WITH 1       
  INCREMENT BY 1    
  MINVALUE 1        
  MAXVALUE 999999999999999999999999999 
  CYCLE           
  CACHE 20;


CREATE PUBLIC SYNONYM SEQ_AUTO_INCREMENT_PROMOCIONES FOR SALUDMP.SEQ_AUTO_INCREMENT_PROMOCIONES;
GRANT SELECT ON  SALUDMP.SEQ_AUTO_INCREMENT_PROMOCIONES TO SALUDMP_APLICACION;


CREATE OR REPLACE TRIGGER AUTO_INCREMENT_PROMOCIONES 
   BEFORE INSERT ON VDIR_PROMOCIONES
   FOR EACH ROW
BEGIN
   SELECT SEQ_AUTO_INCREMENT_PROMOCIONES.nextval
   INTO :new.COD_PROMOCION
   FROM dual;
END;


CREATE PUBLIC SYNONYM AUTO_INCREMENT_PROMOCIONES FOR SALUDMP.AUTO_INCREMENT_PROMOCIONES;
GRANT SELECT ON  SALUDMP.AUTO_INCREMENT_PROMOCIONES TO SALUDMP_APLICACION;

CREATE PUBLIC SYNONYM AUTO_INCREMENT_PROMOCIONES FOR SALUDMP.AUTO_INCREMENT_PROMOCIONES;
GRANT EXECUTE ON  SALUDMP.AUTO_INCREMENT_PROMOCIONES TO SALUDMP_APLICACION;