
CREATE TABLE
    VDIR_BENEFICIARIOS_ASOCIADOS (
        COD_BENEFICIARIO NUMBER(38, 0) NOT NULL,
        NOMBRE_1 VARCHAR2(500 BYTE) NOT NULL,
        NOMBRE_2 VARCHAR2(500 BYTE),
        APELLIDO_1 VARCHAR2(500 BYTE) NOT NULL,
        APELLIDO_2 VARCHAR2(500 BYTE),
        COD_SEXO VARCHAR2(10 BYTE),
        COD_PARENTESCO VARCHAR2(10 BYTE),
        COD_AFILIACION VARCHAR2(10 BYTE),
        CONSTRAINT VDIR_BENEFICIARIOS_ASOCIADOS_COD_BENEFICIARIO_PK PRIMARY KEY (COD_BENEFICIARIO)
    );

CREATE TABLE
    VDIR_PROMOCIONES (
        COD_PROMOCION NUMBER(38, 0) NOT NULL,
        URL_PROMOCION VARCHAR2(500 BYTE) NOT NULL,
        FECHA_INICIO DATE,
        FECHA_FIN DATE,
        COD_ESTADO NUMBER(38, 0),
        CONSTRAINT VDIR_PROMOCIONES_COD_PROMOCION_PK PRIMARY KEY (COD_PROMOCION),
        CONSTRAINT VDIR_PROMOCIONES_COD_ESTADO_FK FOREIGN KEY (COD_ESTADO) REFERENCES VDIR_ESTADO (COD_ESTADO)
    );

CREATE TABLE
    VDIR_TARIFAS_ASOCIADAS (
        COD_BENEFICIARIO NUMBER(38, 0),
        COD_AFILIACION VARCHAR2(10 BYTE),
        COD_PROGRAMA VARCHAR2(10 BYTE),
        CONSTRAINT VDIR_TARIFAS_ASOCIADAS_COD_BENEFICIARIO_PK PRIMARY KEY (COD_BENEFICIARIO)
    );