ALTER TABLE ACEPTA_TERMINOS_INFOMEDICA ADD TIPO_DOC_PRESTADOR VARCHAR2(10);
ALTER TABLE ACEPTA_TERMINOS_INFOMEDICA ADD NUMERO_DOC_PRESTADOR VARCHAR2(30);
ALTER TABLE ACEPTA_TERMINOS_INFOMEDICA ADD NOMBRE_PRESTADOR VARCHAR2(200);


ALTER TABLE ACEPTA_TERMINOS_HD ADD TIPO_DOC_PRESTADOR VARCHAR2(10);
ALTER TABLE ACEPTA_TERMINOS_HD ADD NUMERO_DOC_PRESTADOR VARCHAR2(30);
ALTER TABLE ACEPTA_TERMINOS_HD ADD NOMBRE_PRESTADOR VARCHAR2(200);


