CREATE TABLE "ADM_AGRUPACION" (
  "ID" NUMBER PRIMARY KEY,
  "NOMBRE" VARCHAR2(255) NOT NULL,
  "DESCRIPCION" VARCHAR2(255) NOT NULL,
  "FECHA_CREACION" DATE NOT NULL
);

COMMENT ON TABLE "ADM_AGRUPACION" IS 'Tabla que almacena agrupaciones de coberturas.';
COMMENT ON COLUMN "ADM_AGRUPACION"."ID" IS 'Identificador único de la agrupación.';
COMMENT ON COLUMN "ADM_AGRUPACION"."NOMBRE" IS 'Nombre de la agrupación.';
COMMENT ON COLUMN "ADM_AGRUPACION"."DESCRIPCION" IS 'Descripción detallada de la agrupación.';
COMMENT ON COLUMN "ADM_AGRUPACION"."FECHA_CREACION" IS 'Fecha en que se creó la agrupación.';

CREATE TABLE "ADM_COBERTURA" (
  "ID" NUMBER PRIMARY KEY,
  "ID_AGRUPACION" NUMBER NOT NULL,
  "SERVICIO" VARCHAR2(255) NOT NULL,
  "PROGRAMA" VARCHAR2(255) NOT NULL,
  "APLICACION" VARCHAR2(255) NOT NULL,
  "PERIODO_CARENCIA" VARCHAR2(255) NOT NULL,
  "COBERTURA_MAXIMA" varchar2(255) NOT NULL,
  "ULTIMA_ACTUALIZACION" DATE,
  "FECHA_CREACION" DATE NOT NULL
);

COMMENT ON TABLE "ADM_COBERTURA" IS 'Tabla que almacena la información sobre coberturas dentro de una agrupación.';
COMMENT ON COLUMN "ADM_COBERTURA"."ID" IS 'Identificador único de la cobertura.';
COMMENT ON COLUMN "ADM_COBERTURA"."ID_AGRUPACION" IS 'Referencia a la agrupación a la que pertenece la cobertura.';
COMMENT ON COLUMN "ADM_COBERTURA"."SERVICIO" IS 'Servicio al que aplica la cobertura.';
COMMENT ON COLUMN "ADM_COBERTURA"."PROGRAMA" IS 'Programa relacionado con la cobertura.';
COMMENT ON COLUMN "ADM_COBERTURA"."APLICACION" IS 'Aplicación o contexto de la cobertura.';
COMMENT ON COLUMN "ADM_COBERTURA"."PERIODO_CARENCIA" IS 'Tiempo de espera antes de que la cobertura sea efectiva.';
COMMENT ON COLUMN "ADM_COBERTURA"."COBERTURA_MAXIMA" IS 'Límite máximo de cobertura.';
COMMENT ON COLUMN "ADM_COBERTURA"."ULTIMA_ACTUALIZACION" IS 'Fecha de la última actualización de la cobertura.';
COMMENT ON COLUMN "ADM_COBERTURA"."FECHA_CREACION" IS 'Fecha en que se creó el registro de cobertura.';

ALTER TABLE "ADM_COBERTURA" ADD FOREIGN KEY ("ID_AGRUPACION") REFERENCES "ADM_AGRUPACION" ("ID");

CREATE SEQUENCE SMP_ADM_DESA.ADM_AGRUPACION_SEQ 
    INCREMENT BY 1 
    MINVALUE 1 
    MAXVALUE 999999999999 
    NOCYCLE 
    NOCACHE 
    NOORDER;

CREATE SEQUENCE SMP_ADM_DESA.ADM_COBERTURAS_SEQ 
    INCREMENT BY 1 
    MINVALUE 1 
    MAXVALUE 999999999999 
    NOCYCLE 
    NOCACHE 
    NOORDER;