
DROP TABLE SALUDMP_ADMINAPP.ADM_VERSION_DOCUMENTOS;


CREATE OR REPLACE TRIGGER ADM_VERSION_DOCUMENTOS_ID_TRG
BEFORE INSERT ON ADM_VERSION_DOCUMENTOS
FOR EACH ROW
BEGIN
    IF :new.id IS NULL THEN
        SELECT ADM_VERSION_DOCUMENTOS_ID_SEQ.nextval INTO :new.id FROM DUAL;
    END IF;
END;



CREATE PUBLIC SYNONYM ADM_VERSION_DOCUMENTOS_ID_TRG FOR SALUDMP.ADM_VERSION_DOCUMENTOS_ID_TRG;
GRANT SELECT ON  SALUDMP.ADM_VERSION_DOCUMENTOS_ID_TRG TO SALUDMP_APLICACION;


GRANT SALUDMP_APLICACION TO SALUDMP_ADMINAPP;
