CREATE TABLE
    SALUDMP.ADM_VERSION_DOCUMENTOS (
        ID NUMBER NOT NULL,
        USUARIO VARCHAR2(50) NOT NULL,
        FECHA TIMESTAMP(6) NOT NULL,
        VERSION VARCHAR2(10),
        TIPO_DOCUMENTO VARCHAR2(50),
        DESCRIPCION CLOB NOT NULL,
        CODIGO_APP VARCHAR2(50) NOT NULL,
        CONSTRAINT ADM_VERSION_DOCUMENTOS_PK PRIMARY KEY (ID)
    );


COMMENT ON COLUMN SALUDMP.ADM_VERSION_DOCUMENTOS.ID IS 'COLUMNA DE IDENTIFICACION DE REGISTRO';

COMMENT ON COLUMN SALUDMP.ADM_VERSION_DOCUMENTOS.USUARIO IS 'HACE REFERENCIA AL USUARIO QUE CREA EL DOCUMENTO';

COMMENT ON COLUMN SALUDMP.ADM_VERSION_DOCUMENTOS.FECHA IS 'HACE REFERENCIA A LA FECHA DE CREACIÓN DEL DOCUMENTO';

COMMENT ON COLUMN SALUDMP.ADM_VERSION_DOCUMENTOS.VERSION IS 'HACE REFERENCIA A LA VERSIÓN DEL DOCUMENTO CREADO';

COMMENT ON COLUMN SALUDMP.ADM_VERSION_DOCUMENTOS.TIPO_DOCUMENTO IS 'HACE REFERENCIA AL TIPO DE DOCUMENTO CREADO';

COMMENT ON COLUMN SALUDMP.ADM_VERSION_DOCUMENTOS.DESCRIPCION IS 'HACE REFERENCIA AL CONTENIDO DEL DOCUMENTO CREADO';

COMMENT ON COLUMN SALUDMP.ADM_VERSION_DOCUMENTOS.CODIGO_APP IS 'HACE REFERENCIA AL CONTENIDO DEL DOCUMENTO CREADO';