CREATE TABLE
    ADM_PROGRAMA_VISOR (
        PROGRAMA_GRUPO VARCHAR2(10) NOT NULL ENABLE,
        CARTILLA VARCHAR2(10) NOT NULL ENABLE,
        DESC_GRUPO VARCHAR2(60) NOT NULL ENABLE,
        IMAGEN_PROGRAMA CLOB NOT NULL ENABLE,
        ESTADO NUMBER(1) DEFAULT 1 NOT NULL ENABLE,
        TIPO_SERVICIO VARCHAR2(20)
    )