alter table ADM_CENTRO_NOTIFICACIONES add ESTADO VARCHAR2(10);
alter table ADM_CENTRO_NOTIFICACIONES add FEC_ESTADO DATE;

COMMENT ON COLUMN ADM_CENTRO_NOTIFICACIONES.ESTADO IS 'Estado del mensaje(NULL(NUEVO)/NO LEIDO/LEIDO/ELIMINADO)';
COMMENT ON COLUMN ADM_CENTRO_NOTIFICACIONES.FEC_ESTADO IS 'FECHA DEL ULTIMO CAMBIO DE ESTADO';