UPDATE est_parametro SET descripcion = '¿Como Usar Dental Elite?', fecha_registro = SYSDATE, estado = 0 WHERE cod_funcion = 'DEN'; 
UPDATE est_parametro SET descripcion = 'Consultas Canal YouTube Coomeva Salud Oral', fecha_registro = SYSDATE, estado= 0 WHERE cod_funcion = 'YTB'; 
UPDATE est_parametro SET descripcion = 'Visualización Estado de Cuenta', fecha_registro = SYSDATE, estado= 0 WHERE cod_funcion = 'PGV'; 
UPDATE est_parametro SET descripcion = 'Envío de Estado de cuenta a Correo electrnico', fecha_registro = SYSDATE, estado= 0 WHERE cod_funcion = 'PGC'; 
UPDATE est_parametro SET descripcion = 'Pago electrónico Estado de cuenta Asociado Payu', fecha_registro = SYSDATE, estado= 0 WHERE cod_funcion = 'PEA'; 
UPDATE est_parametro SET descripcion = 'Citas Médicas - Consultar disponibilidad de citas', fecha_registro = SYSDATE, estado= 1 WHERE cod_funcion = 'CDC'; 
UPDATE est_parametro SET descripcion = 'Centro Médico Virtual - Medico Domiciliario + Consulta Directorio', fecha_registro = SYSDATE, estado= 1 WHERE cod_funcion = 'MMC'; 
UPDATE est_parametro SET descripcion = 'Contactenos - Consultar las líneas de atención telefónica', fecha_registro = SYSDATE, estado= 1 WHERE cod_funcion = 'OVC'; 


INSERT INTO est_parametro ( cod_funcion, descripcion, fecha_registro, cod_parametro, tipo_funcionalidad, estado ) VALUES ('CCA','Citas Médicas - Visualizar Citas Asignadas',SYSDATE,102,NULL,1); 
INSERT INTO est_parametro ( cod_funcion, descripcion, fecha_registro, cod_parametro, tipo_funcionalidad, estado ) VALUES ('CHC','Citas Médicas - Histórico de citas asignadas',SYSDATE,103,NULL,1); 
INSERT INTO est_parametro ( cod_funcion, descripcion, fecha_registro, cod_parametro, tipo_funcionalidad, estado ) VALUES ('CEH','Citas Médicas - Envío por correo de Historia Clínica',SYSDATE,104,NULL,1); 
INSERT INTO est_parametro ( cod_funcion, descripcion, fecha_registro, cod_parametro, tipo_funcionalidad, estado ) VALUES ('CRC','Citas Médicas - Reprogramar citas',SYSDATE,105,NULL,1); 
INSERT INTO est_parametro ( cod_funcion, descripcion, fecha_registro, cod_parametro, tipo_funcionalidad, estado ) VALUES ('ACA','Autorizaciones - Consultar una solicitud de autorización',SYSDATE,106,NULL,1); 
INSERT INTO est_parametro ( cod_funcion, descripcion, fecha_registro, cod_parametro, tipo_funcionalidad, estado ) VALUES ('AVR','Autorizaciones - Visualizar Respuesta',SYSDATE,107,NULL,1); 
INSERT INTO est_parametro ( cod_funcion, descripcion, fecha_registro, cod_parametro, tipo_funcionalidad, estado ) VALUES ('AVA','Autorizaciones - Visualizar Achivos',SYSDATE,108,NULL,1); 
INSERT INTO est_parametro ( cod_funcion, descripcion, fecha_registro, cod_parametro, tipo_funcionalidad, estado ) VALUES ('ADA','Autorizaciones - Descargar Archivos IOS',SYSDATE,109,NULL,1); 
INSERT INTO est_parametro ( cod_funcion, descripcion, fecha_registro, cod_parametro, tipo_funcionalidad, estado ) VALUES ('ACA','Autorizaciones - Compartir Archivos',SYSDATE,110,NULL,1); 
INSERT INTO est_parametro ( cod_funcion, descripcion, fecha_registro, cod_parametro, tipo_funcionalidad, estado ) VALUES ('MMD','Centro Médico Virtual - Medico Domiciliario + Llamada #586',SYSDATE,111,NULL,1); 
INSERT INTO est_parametro ( cod_funcion, descripcion, fecha_registro, cod_parametro, tipo_funcionalidad, estado ) VALUES ('MOM','Centro Médico Virtual - Orientación Médica en Linea',SYSDATE,112,NULL,1); 
INSERT INTO est_parametro ( cod_funcion, descripcion, fecha_registro, cod_parametro, tipo_funcionalidad, estado ) VALUES ('MTC','Centro Médico Virtual - Tele Consulta',SYSDATE,113,NULL,1); 
INSERT INTO est_parametro ( cod_funcion, descripcion, fecha_registro, cod_parametro, tipo_funcionalidad, estado ) VALUES ('DEC','Directorio Médico - Especialidad (Consultas Médicas)',SYSDATE,114,NULL,1); 
INSERT INTO est_parametro ( cod_funcion, descripcion, fecha_registro, cod_parametro, tipo_funcionalidad, estado ) VALUES ('DPC','Directorio Médico - Prestador, Clínica o Intitución Médica',SYSDATE,115,NULL,1); 
INSERT INTO est_parametro ( cod_funcion, descripcion, fecha_registro, cod_parametro, tipo_funcionalidad, estado ) VALUES ('PRP','Pagos - Registro de Pago Automático',SYSDATE,116,NULL,1); 
INSERT INTO est_parametro ( cod_funcion, descripcion, fecha_registro, cod_parametro, tipo_funcionalidad, estado ) VALUES ('RRE','Resultados de Exámenes e Historia Clínicas - Resultados de Examenes',SYSDATE,117,NULL,1); 
INSERT INTO est_parametro ( cod_funcion, descripcion, fecha_registro, cod_parametro, tipo_funcionalidad, estado ) VALUES ('RHC','Resultados de Exámenes e Historia Clínicas - Historia Clínica',SYSDATE,118,NULL,1); 
INSERT INTO est_parametro ( cod_funcion, descripcion, fecha_registro, cod_parametro, tipo_funcionalidad, estado ) VALUES ('RHR','Resultados de Exámenes e Historia Clínicas - Historia Clínica - Reprogramar',SYSDATE,119,NULL,1); 
INSERT INTO est_parametro ( cod_funcion, descripcion, fecha_registro, cod_parametro, tipo_funcionalidad, estado ) VALUES ('RHE','Resultados de Exámenes e Historia Clínicas - Historia Clínica - Remisiones',SYSDATE,120,NULL,1); 
INSERT INTO est_parametro ( cod_funcion, descripcion, fecha_registro, cod_parametro, tipo_funcionalidad, estado ) VALUES ('CMV','Centros Médicos - Visualizar Información Centros Médicos',SYSDATE,121,NULL,1); 
INSERT INTO est_parametro ( cod_funcion, descripcion, fecha_registro, cod_parametro, tipo_funcionalidad, estado ) VALUES ('CSC','Configuración de Seguridad - Configurar logueo por huella digital o FaceID',SYSDATE,122,NULL,1); 
INSERT INTO est_parametro ( cod_funcion, descripcion, fecha_registro, cod_parametro, tipo_funcionalidad, estado ) VALUES ('RAP','Referidos - Acceder al portal de referidos',SYSDATE,123,NULL,1); 
INSERT INTO est_parametro ( cod_funcion, descripcion, fecha_registro, cod_parametro, tipo_funcionalidad, estado ) VALUES ('MSP','Centro de Mensajes - Visualizar Mensajes Push',SYSDATE,124,NULL,1); 
INSERT INTO est_parametro ( cod_funcion, descripcion, fecha_registro, cod_parametro, tipo_funcionalidad, estado ) VALUES ('MSL','Centro de Mensajes - Marcar como leido',SYSDATE,125,NULL,1); 
INSERT INTO est_parametro ( cod_funcion, descripcion, fecha_registro, cod_parametro, tipo_funcionalidad, estado ) VALUES ('MSE','Centro de Mensajes - Eliminar mensaje',SYSDATE,126,NULL,1); 
INSERT INTO est_parametro ( cod_funcion, descripcion, fecha_registro, cod_parametro, tipo_funcionalidad, estado ) VALUES ('ICC','Información - Canales de Comunicación',SYSDATE,127,NULL,1); 
INSERT INTO est_parametro ( cod_funcion, descripcion, fecha_registro, cod_parametro, tipo_funcionalidad, estado ) VALUES ('IPT','Información - Politica de tratamiento de datos',SYSDATE,128,NULL,1); 
INSERT INTO est_parametro ( cod_funcion, descripcion, fecha_registro, cod_parametro, tipo_funcionalidad, estado ) VALUES ('ITC','Información - Terminos y condiciones',SYSDATE,129,NULL,1); 
INSERT INTO est_parametro ( cod_funcion, descripcion, fecha_registro, cod_parametro, tipo_funcionalidad, estado ) VALUES ('IRV','Información - Registro de Pago Automático para Ventas',SYSDATE,130,NULL,1); 
INSERT INTO est_parametro ( cod_funcion, descripcion, fecha_registro, cod_parametro, tipo_funcionalidad, estado ) VALUES ('OUT','Cerra sesión - Permite al usuario salir de la cuenta ',SYSDATE,131,NULL,1); 